version: "3.8"

x-hashicorp-config: &hashicorp-config
  CONSUL_ADDR: "${CONSUL_ADDR}"
  NOMAD_ADDR: "${NOMAD_ADDR}"
  VAULT_ADDR: "${VAULT_ADDR}"
  VAULT_TOKEN: "${VAULT_TOKEN}"
  DEPLOY_CONFIG: "${DEPLOY_CONFIG}"
  VERSION: "${VERSION}"

services:
  # deploy all nomad jobs
  deploy:
    environment:
      <<: *hashicorp-config
    image: debian:10.6-slim
    entrypoint: [ "/scripts/deploy.sh" ]
    volumes:
      - ./:/source
    working_dir: /source

  # upload all config files to consul
  config:
    environment:
      <<: *hashicorp-config
    image: ghcr.io/pennsignals/consul_configs_submit_action/consul_configs_submit_action.consul:1.0.0
    volumes:
      - ./:/source/
    working_dir: /source

  # get secrets from vault
  secrets_get:
    command:
      - "--get"
    environment:
      <<: *hashicorp-config
    image: ghcr.io/pennsignals/secrets/secrets.vault:1.2.0
    volumes:
      - ./:/source/
    working_dir: /source

  # put secrets to vault
  secrets_put:
    command:
      - "--put"
    environment:
      <<: *hashicorp-config
    image: ghcr.io/pennsignals/secrets/secrets.vault:1.2.0
    volumes:
      - ./:/source/
    working_dir: /source
