ARG PYTHON_VERSION="3.9"
ARg ROOT_CONTAINER=python:${PYTHON_VERSION}-slim-bullseye

ARG IFLAGS="--quiet --no-cache-dir --user"

FROM ${ROOT_CONTAINER} as binaries
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
USER root
WORKDIR /tmp
ENV DEBIAN_FRONTEND noninteractive
RUN \
    apt-get -qq update --yes && \
    apt-get -qq upgrade --yes && \
    apt-get -qq install --yes --no-install-recommends \
	gcc \
	git \
	libc6-dev \
	libyaml-dev \
	tini \
    > /dev/null && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install -U pip setuptools wheel
ENTRYPOINT ["/usr/bin/tini", "-g", "--"]


FROM binaries as source
COPY . .


FROM source as pre-commit
RUN \
    pip install ".[dev]"
CMD pre-commit run --all-files


FROM source as test
RUN \
    pip install ".[dev]"
CMD pytest


FROM source as build-wheel
CMD pip wheel --no-deps -w ./dist .


FROM binaries as install-wheel
CMD pip install --find-links=./dist {{coockiecutter.name}}[dev]


FROM source as build-predict
RUN \
    pip wheel --no-deps -w ./dist .


FROM binaries as predict
COPY --from=source /etc/freetds/freetds.conf /etc/freetds/
COPY --from=source /tmp/predict/sql /tmp/predict/sql
COPY --from=build-predict /tmp/dist/ /tmp/dist
RUN \
    ln -s /local ./predict/local && \
    ln -s /secrets ./predict/secrets && \
    ln -s /model ./predict/model && \
    ln -s /gold ./predict/gold && \
    pip install --find-links=./dist {{coockiecutter.name}}
CMD ["predict"]
